server:
  port: 9100

spring:
  application:
    name: vwe_buz_blog
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/asa_vwe?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: root
    password: 123456


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7761/eureka/
