server:
  port: 9100

spring:
  application:
    name: vwe_buz_blog
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/asa_vwe?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7761/eureka/

logging:
  level:
    root: info
    pers:
      demo:
        asa:
          vwe:
            blog:
              dao: trace

#mybatis-plus config:
mybatis-plus:
  mapper-locations: classpath*:pers/demo/asa/vwe/blog/mapper/**/*.xml