server:
  port: 9210
spring:
  application:
    name: vwe-comments
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7761/eureka/

logging:
  level:
    root: info
    pers:
      demo:
        asa:
          vwe:
            comments:
              dao: trace

#mybatis-plus config:
mybatis-plus:
  mapper-locations: classpath*:pers/demo/asa/vwe/comments/mapper/**/*.xml