server:
  port: 9000

#注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
jwt:
  secret: hello,jwt!

spring:
  application:
    name: cloud-gateway-jwt
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: service-hi
          uri: lb://SERVICE-HI
          predicates:
            - Path=/api/service/hi/**
          filters:
            - StripPrefix=1
        - id: service-order
          uri: lb://SERVICE-ORDER
          predicates:
            - Path=/api/service/order/**
          filters:
            - StripPrefix=1
        - id: service-user
          uri: localhost:${server.port}
          predicates:
            - Path=/api/service/user/**
          filters:
            - StripPrefix=1
#            - name: Logging
#              args:
#                baseMessage: Custom filter factory
#                preLogger: true
#                postLogger: true

config:
  security:
    ignoreUrls:
      - /api/service/user/authentication
      - /api/service/user/login

