spring:
  datasource:
    url: jdbc:mysql://localhost:3306/asa_vwe_parent?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: asa123X$_vp
    username: vwe_prod