package pers.demo.asa.vwe.comments.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pers.demo.asa.vwe.comments.model.VWECommentsModel;
import pers.demo.asa.vwe.comments.model.VWECommentsModelExample;
import pers.demo.asa.vwe.common.dao.BaseDao;

public interface VWECommentsModelMapper extends BaseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vwe_comments
     *
     * @mbg.generated
     */
    long countByExample(VWECommentsModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vwe_comments
     *
     * @mbg.generated
     */
    int deleteByExample(VWECommentsModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vwe_comments
     *
     * @mbg.generated
     */
    int insert(VWECommentsModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vwe_comments
     *
     * @mbg.generated
     */
    int insertSelective(VWECommentsModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vwe_comments
     *
     * @mbg.generated
     */
    List<VWECommentsModel> selectByExample(VWECommentsModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vwe_comments
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") VWECommentsModel record, @Param("example") VWECommentsModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vwe_comments
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") VWECommentsModel record, @Param("example") VWECommentsModelExample example);
}