server:
  port: 9200

spring:
  application:
    name: vwe-biz-comments
  datasource:
    url: jdbc:mysql://localhost:3306/asa_vwe_parent?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: asa123X_RT
    username: remote_test

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7761/eureka/

logging:
  level:
    root: info
    pers:
      demo:
        asa:
          vwe:
            comments:
              dao: trace

#mybatis-plus config:
mybatis-plus:
  mapper-locations: classpath*:pers/demo/asa/vwe/comments/mapper/**/*.xml