package pers.demo.asa.vwe.comments.model;

import pers.demo.asa.vwe.common.model.BaseModel;

public class VWECommentsModel extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vwe_comments.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vwe_comments.blog_id
     *
     * @mbg.generated
     */
    private String blog_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vwe_comments.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vwe_comments.ref_id
     *
     * @mbg.generated
     */
    private String ref_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vwe_comments.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vwe_comments.sub_comments
     *
     * @mbg.generated
     */
    private String sub_comments;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vwe_comments
     *
     * @mbg.generated
     */
    public VWECommentsModel(String content, String blog_id, String email, String ref_id, String remark, String sub_comments) {
        this.content = content;
        this.blog_id = blog_id;
        this.email = email;
        this.ref_id = ref_id;
        this.remark = remark;
        this.sub_comments = sub_comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vwe_comments.content
     *
     * @return the value of vwe_comments.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vwe_comments.blog_id
     *
     * @return the value of vwe_comments.blog_id
     *
     * @mbg.generated
     */
    public String getBlog_id() {
        return blog_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vwe_comments.email
     *
     * @return the value of vwe_comments.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vwe_comments.ref_id
     *
     * @return the value of vwe_comments.ref_id
     *
     * @mbg.generated
     */
    public String getRef_id() {
        return ref_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vwe_comments.remark
     *
     * @return the value of vwe_comments.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vwe_comments.sub_comments
     *
     * @return the value of vwe_comments.sub_comments
     *
     * @mbg.generated
     */
    public String getSub_comments() {
        return sub_comments;
    }
}