package pers.demo.asa.vwe.comments.model;

import java.util.ArrayList;
import java.util.List;

public class VWECommentsModelExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vwe_comments
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vwe_comments
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vwe_comments
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vwe_comments
     *
     * @mbg.generated
     */
    public VWECommentsModelExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vwe_comments
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vwe_comments
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vwe_comments
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vwe_comments
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vwe_comments
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vwe_comments
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vwe_comments
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vwe_comments
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vwe_comments
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vwe_comments
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vwe_comments
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andContentIsNull() {
            addCriterion("content is null");
            return (Criteria) this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("content is not null");
            return (Criteria) this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("content =", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("content <>", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("content >", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("content >=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("content <", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("content <=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("content like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("content not like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentIn(List<String> values) {
            addCriterion("content in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotIn(List<String> values) {
            addCriterion("content not in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("content between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("content not between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andBlog_idIsNull() {
            addCriterion("blog_id is null");
            return (Criteria) this;
        }

        public Criteria andBlog_idIsNotNull() {
            addCriterion("blog_id is not null");
            return (Criteria) this;
        }

        public Criteria andBlog_idEqualTo(String value) {
            addCriterion("blog_id =", value, "blog_id");
            return (Criteria) this;
        }

        public Criteria andBlog_idNotEqualTo(String value) {
            addCriterion("blog_id <>", value, "blog_id");
            return (Criteria) this;
        }

        public Criteria andBlog_idGreaterThan(String value) {
            addCriterion("blog_id >", value, "blog_id");
            return (Criteria) this;
        }

        public Criteria andBlog_idGreaterThanOrEqualTo(String value) {
            addCriterion("blog_id >=", value, "blog_id");
            return (Criteria) this;
        }

        public Criteria andBlog_idLessThan(String value) {
            addCriterion("blog_id <", value, "blog_id");
            return (Criteria) this;
        }

        public Criteria andBlog_idLessThanOrEqualTo(String value) {
            addCriterion("blog_id <=", value, "blog_id");
            return (Criteria) this;
        }

        public Criteria andBlog_idLike(String value) {
            addCriterion("blog_id like", value, "blog_id");
            return (Criteria) this;
        }

        public Criteria andBlog_idNotLike(String value) {
            addCriterion("blog_id not like", value, "blog_id");
            return (Criteria) this;
        }

        public Criteria andBlog_idIn(List<String> values) {
            addCriterion("blog_id in", values, "blog_id");
            return (Criteria) this;
        }

        public Criteria andBlog_idNotIn(List<String> values) {
            addCriterion("blog_id not in", values, "blog_id");
            return (Criteria) this;
        }

        public Criteria andBlog_idBetween(String value1, String value2) {
            addCriterion("blog_id between", value1, value2, "blog_id");
            return (Criteria) this;
        }

        public Criteria andBlog_idNotBetween(String value1, String value2) {
            addCriterion("blog_id not between", value1, value2, "blog_id");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andRef_idIsNull() {
            addCriterion("ref_id is null");
            return (Criteria) this;
        }

        public Criteria andRef_idIsNotNull() {
            addCriterion("ref_id is not null");
            return (Criteria) this;
        }

        public Criteria andRef_idEqualTo(String value) {
            addCriterion("ref_id =", value, "ref_id");
            return (Criteria) this;
        }

        public Criteria andRef_idNotEqualTo(String value) {
            addCriterion("ref_id <>", value, "ref_id");
            return (Criteria) this;
        }

        public Criteria andRef_idGreaterThan(String value) {
            addCriterion("ref_id >", value, "ref_id");
            return (Criteria) this;
        }

        public Criteria andRef_idGreaterThanOrEqualTo(String value) {
            addCriterion("ref_id >=", value, "ref_id");
            return (Criteria) this;
        }

        public Criteria andRef_idLessThan(String value) {
            addCriterion("ref_id <", value, "ref_id");
            return (Criteria) this;
        }

        public Criteria andRef_idLessThanOrEqualTo(String value) {
            addCriterion("ref_id <=", value, "ref_id");
            return (Criteria) this;
        }

        public Criteria andRef_idLike(String value) {
            addCriterion("ref_id like", value, "ref_id");
            return (Criteria) this;
        }

        public Criteria andRef_idNotLike(String value) {
            addCriterion("ref_id not like", value, "ref_id");
            return (Criteria) this;
        }

        public Criteria andRef_idIn(List<String> values) {
            addCriterion("ref_id in", values, "ref_id");
            return (Criteria) this;
        }

        public Criteria andRef_idNotIn(List<String> values) {
            addCriterion("ref_id not in", values, "ref_id");
            return (Criteria) this;
        }

        public Criteria andRef_idBetween(String value1, String value2) {
            addCriterion("ref_id between", value1, value2, "ref_id");
            return (Criteria) this;
        }

        public Criteria andRef_idNotBetween(String value1, String value2) {
            addCriterion("ref_id not between", value1, value2, "ref_id");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andSub_commentsIsNull() {
            addCriterion("sub_comments is null");
            return (Criteria) this;
        }

        public Criteria andSub_commentsIsNotNull() {
            addCriterion("sub_comments is not null");
            return (Criteria) this;
        }

        public Criteria andSub_commentsEqualTo(String value) {
            addCriterion("sub_comments =", value, "sub_comments");
            return (Criteria) this;
        }

        public Criteria andSub_commentsNotEqualTo(String value) {
            addCriterion("sub_comments <>", value, "sub_comments");
            return (Criteria) this;
        }

        public Criteria andSub_commentsGreaterThan(String value) {
            addCriterion("sub_comments >", value, "sub_comments");
            return (Criteria) this;
        }

        public Criteria andSub_commentsGreaterThanOrEqualTo(String value) {
            addCriterion("sub_comments >=", value, "sub_comments");
            return (Criteria) this;
        }

        public Criteria andSub_commentsLessThan(String value) {
            addCriterion("sub_comments <", value, "sub_comments");
            return (Criteria) this;
        }

        public Criteria andSub_commentsLessThanOrEqualTo(String value) {
            addCriterion("sub_comments <=", value, "sub_comments");
            return (Criteria) this;
        }

        public Criteria andSub_commentsLike(String value) {
            addCriterion("sub_comments like", value, "sub_comments");
            return (Criteria) this;
        }

        public Criteria andSub_commentsNotLike(String value) {
            addCriterion("sub_comments not like", value, "sub_comments");
            return (Criteria) this;
        }

        public Criteria andSub_commentsIn(List<String> values) {
            addCriterion("sub_comments in", values, "sub_comments");
            return (Criteria) this;
        }

        public Criteria andSub_commentsNotIn(List<String> values) {
            addCriterion("sub_comments not in", values, "sub_comments");
            return (Criteria) this;
        }

        public Criteria andSub_commentsBetween(String value1, String value2) {
            addCriterion("sub_comments between", value1, value2, "sub_comments");
            return (Criteria) this;
        }

        public Criteria andSub_commentsNotBetween(String value1, String value2) {
            addCriterion("sub_comments not between", value1, value2, "sub_comments");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vwe_comments
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vwe_comments
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}